version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./:/usr/app/
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    expose:
      - '8080'
    ports:
      - '8080:3000'
    container_name: github-repos-api
    entrypoint: ./entry-point.sh
    command: [/usr/app/development-entry.sh]
